//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public AccessLog()
        {
            this.id = Guid.NewGuid();
        }
        public System.Guid id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string user_full_name { get; set; }
        public string ip_address { get; set; }
        public string machine_name { get; set; }
        public string operation { get; set; }
        public string object_info { get; set; }
        public string browser_info { get; set; }
    }
}
