//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.id = Guid.NewGuid();
        }
        public System.Guid id { get; set; }
        public string nonce { get; set; }
        public string user_name { get; set; }
        public System.DateTime date { get; set; }
    }
}
