//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lu_CountryOfOrigin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_lu_CountryOfOrigin()
        {
           this.Id = Guid.NewGuid();
            this.tblPermits = new HashSet<tblPermit>();
        }

        public System.Guid Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<tblPermit> tblPermits { get; set; }
    }
}
