//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblApplicationAmount
    {
        public tblApplicationAmount()
        {
            this.Id = Guid.NewGuid();
        }
        public System.Guid Id { get; set; }
        public System.Guid ApplicationId { get; set; }
        public System.Guid ApprovalStatusId { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountInUSD { get; set; }
        public Nullable<decimal> AmountInBirr { get; set; }
        public Nullable<decimal> USDRate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }    
        public virtual tbl_lu_Status tbl_lu_Status { get; set; }
        public virtual tblApplication tblApplication { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        //#
        public string ApplicantName { get; set; }
        public string CIFNumber { get; set; }
        public string PermitStatus { get; set; }
        public string ApprovalStatus { get; set; }
        public string NBEApprovalRefNumber { get; set; }
        public string QueueRound { get; set; }
        public string QueueNumber { get; set; }
        public string OwnSourceValue { get; set; }
        public string PurposeOfPayment { get; set; }
        public string CurrencyRateValue { get; set; }
        [Display(Name = "Amount")]
        [RegularExpression(@"^(\-)?\d{1,3}(?:,\d{3})*(?:\.\d{1,6})?$", ErrorMessage = "Amount should be a number greater than 0.")]
        public string AmountValue { get; set; }
        [Display(Name = "USD Rate")]
        public string USDRateValue { get; set; }
        [Display(Name = "USD amount")]
        public string AmountInUSDValue { get; set; }
        [Display(Name = "ETB amount")]
        public string AmountInBirrValue { get; set; }
        public string Beneficiary { get; set; }
        public string CurrencyType { get; set; }
        public Guid ApplicantId { get; set; }
        public Nullable<decimal> PreviousAmountValue { get; set; }
        public string CreatedByFullName { get; set; }
        //#
    }
}
