//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemPriority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItemPriority()
        {
            this.Id = Guid.NewGuid();
            this.tblPermits = new HashSet<tblPermit>();
        }
    
        public System.Guid Id { get; set; }
        public string Priority { get; set; }
        public string GroupBy { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermit> tblPermits { get; set; }
        //#
        public string GroupByValue { get; set; }
        public bool is_new { get; set; }
        //#
    }
}
