//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMerchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMerchant()
        {
            this.Id = Guid.NewGuid();
            this.tblPermits = new HashSet<tblPermit>();
        }
    
        public System.Guid Id { get; set; }
        public string TinNumber { get; set; }
        public string ImporterName { get; set; }
        public string TradeName { get; set; }
        public string NBENumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermit> tblPermits { get; set; }
        //#
        public string OldTinNumber { get; set; }
        public string OldNBENumber { get; set; }
        //#
    }
}
