//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tblPermit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPermit()
        {
            this.Id = Guid.NewGuid();
            this.tblPermitAmounts = new HashSet<tblPermitAmount>();
            this.tbl_lu_CountryOfOrigin = new HashSet<tbl_lu_CountryOfOrigin>();
            this.tblPOPermitDetails = new HashSet<tblPOPermitDetail>();
            this.tblPOPermitDetails1 = new HashSet<tblPOPermitDetail>();
            this.tbl_lu_Incoterm = new HashSet<tbl_lu_Incoterm>();
            this.tblItemPriorities = new HashSet<tblItemPriority>();
            this.tbl_lu_PortOfDestination = new HashSet<tbl_lu_PortOfDestination>();
            this.tbl_lu_PortOfLoading = new HashSet<tbl_lu_PortOfLoading>();
            this.tbl_lu_ShipmentAllowedBy = new HashSet<tbl_lu_ShipmentAllowedBy>();
            this.tblPOPermitAmountDetails = new HashSet<tblPOPermitAmountDetail>();
            this.tblPOPermitExpiries = new HashSet<tblPOPermitExpiry>();
            //#
            this.selectedFirstPriorityTopLevels = new List<string>();
            this.selectedFirstPrioritySubLevels = new List<string>();
            this.selectedSecondPriorityTopLevels = new List<string>();
            this.selectedSecondPrioritySubLevels = new List<string>();
            this.selectedThirdPriorityTopLevels = new List<string>();
            this.selectedThirdPrioritySubLevels = new List<string>();
            this.SelectedPortOfLoadingIds = new List<Guid>();
            this.SelectedPortOfDestinationIds = new List<Guid>();
            this.SelectedShipmentAllowedByIds = new List<Guid>();
            this.SelectedIncotermIds = new List<Guid>();
            this.SelectedCountryOfOriginIds = new List<Guid>();
            this.SelectedPurchaseOrderIds = new List<Guid>();
            //#
        }

        public System.Guid Id { get; set; }
        public string PermitNumber { get; set; }
        public System.Guid MerchantId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> PermitStatusId { get; set; }
        public string PermitType { get; set; }
        public System.Guid SerialNumberShelfId { get; set; }
        public string PermitYear { get; set; }
        public string LPCONumber { get; set; }
        public string CurrencyType { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<decimal> USDRate { get; set; }
        public Nullable<decimal> AmountInUSD { get; set; }
        public Nullable<decimal> RemainingAmountInUSD { get; set; }
        public Nullable<decimal> AmountInBirr { get; set; }
        public Nullable<decimal> RemainingAmountInBirr { get; set; }
        public Nullable<System.Guid> MethodOfPaymentId { get; set; }
        public string NonPriorityItems { get; set; }
        public string ApprovalStatus { get; set; }
        public string NBEApprovalRefNumber { get; set; }
        public string QueueRound { get; set; }
        public string QueueNumber { get; set; }
        public string OwnSourceValue { get; set; }
        public Nullable<decimal> IncreasedAmount { get; set; }
        public Nullable<decimal> IncreasedAmountInUSD { get; set; }
        public Nullable<decimal> IncreasedAmountInBirr { get; set; }
        public Nullable<decimal> DecreasedAmount { get; set; }
        public Nullable<decimal> DecreasedAmountInUSD { get; set; }
        public Nullable<decimal> DecreasedAmountInBirr { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }

        public virtual tbl_lu_MethodOfPayment tbl_lu_MethodOfPayment { get; set; }
        public virtual tbl_lu_Status tbl_lu_Status { get; set; }
        public virtual tblMerchant tblMerchant { get; set; }
        public virtual tblPermit tblPermit1 { get; set; }
        public virtual tblPermit tblPermit2 { get; set; }
        public virtual USER USER { get; set; }
        public virtual tblSerialNumberShelf tblSerialNumberShelf { get; set; }
        public virtual ICollection<tblPermitAmount> tblPermitAmounts { get; set; }
        public virtual ICollection<tblPOPermitAmountDetail> tblPOPermitAmountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOPermitExpiry> tblPOPermitExpiries { get; set; }
        public virtual ICollection<tbl_lu_CountryOfOrigin> tbl_lu_CountryOfOrigin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOPermitDetail> tblPOPermitDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPOPermitDetail> tblPOPermitDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lu_Incoterm> tbl_lu_Incoterm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemPriority> tblItemPriorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lu_PortOfDestination> tbl_lu_PortOfDestination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lu_PortOfLoading> tbl_lu_PortOfLoading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lu_ShipmentAllowedBy> tbl_lu_ShipmentAllowedBy { get; set; }

        //#
        public string ImporterName { get; set; }
        public string Status { get; set; }
        public string TinNumber { get; set; }
        public string NBENumber { get; set; }
        public string ApplicantName { get; set; }
        public string CIFNumber { get; set; }
        public string CurrencyRateValue { get; set; }
        [Display(Name = "Amount")]
        [RegularExpression(@"^\d{1,3}(?:,\d{3})*(?:\.\d{1,6})?$", ErrorMessage = "Amount should be a number greater than 0.")]
        public string AmountValue { get; set; }
        [Display(Name = "Amount")]
        [RegularExpression(@"^(\-)?\d{1,3}(?:,\d{3})*(?:\.\d{1,6})?$", ErrorMessage = "Amount should be a number greater than 0.")]
        public string AmountUpdateValue { get; set; }
        [Display(Name = "USD Rate")]
        public string USDRateValue { get; set; }
        [Display(Name = "USD amount")]
        public string AmountInUSDValue { get; set; }
        [Display(Name = "ETB amount")]
        public string AmountInBirrValue { get; set; }
        public List<string> selectedFirstPriorityTopLevels { get; set; }
        public IEnumerable<SelectListItem> firstPriorityTopLevels { get; set; }
        public List<string> selectedFirstPrioritySubLevels { get; set; }
        public IEnumerable<SelectListItem> firstPrioritySubLevels { get; set; }
        public List<string> selectedSecondPriorityTopLevels { get; set; }
        public IEnumerable<SelectListItem> secondPriorityTopLevels { get; set; }
        public List<string> selectedSecondPrioritySubLevels { get; set; }
        public IEnumerable<SelectListItem> secondPrioritySubLevels { get; set; }
        public List<string> selectedThirdPriorityTopLevels { get; set; }
        public IEnumerable<SelectListItem> thirdPriorityTopLevels { get; set; }
        public List<string> selectedThirdPrioritySubLevels { get; set; }
        public IEnumerable<SelectListItem> thirdPrioritySubLevels { get; set; }
        public List<Guid> SelectedPortOfLoadingIds { get; set; }
        public List<Guid> SelectedPortOfDestinationIds { get; set; }
        public List<Guid> SelectedShipmentAllowedByIds { get; set; }
        public List<Guid> SelectedIncotermIds { get; set; }
        public List<Guid> SelectedCountryOfOriginIds { get; set; }
        public List<Guid> SelectedPurchaseOrderIds { get; set; }

        [Display(Name = "Expiry days")]
        [RegularExpression(@"^\d{1,5}$", ErrorMessage = "Expiry days should be a number greater than 0.")]
        public string ExpiryDays { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public List<tblPermit> ImportPOList { get; set; }
        public string ExpiredYesNo { get; set; }
        public Nullable<bool> ChargeCollected { get; set; }
        public string CountryOfOriginNames { get; set; }
        public string POCurrencyType { get; set; }
        public string PermitNumberCurrencyType
        {
            get
            {
                return this.PermitNumber + " [" + this.CurrencyType + "]";
            }
        }
        public string TypeOfImportPermit { get; set; }
        //#
    }
}
