//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblPermitAmount
    {
        public tblPermitAmount()
        {
            this.Id = Guid.NewGuid();
            this.tblPermitAmountDetails = new HashSet<tblPermitAmountDetail>();
            this.tblPOPermitAmountDetails = new HashSet<tblPOPermitAmountDetail>();
        }
        public System.Guid Id { get; set; }
        public System.Guid PermitId { get; set; }
        public System.Guid ApprovalStatusId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }
    
        public virtual tbl_lu_Status tbl_lu_Status { get; set; }
        public virtual tblPermit tblPermit { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        public virtual ICollection<tblPermitAmountDetail> tblPermitAmountDetails { get; set; }
        public virtual ICollection<tblPOPermitAmountDetail> tblPOPermitAmountDetails { get; set; }

        //#
        public string ImporterName { get; set; }
        public string TinNumber { get; set; }
        public string NBENumber { get; set; }
        public string PermitStatus { get; set; }
        public string ApprovalStatus { get; set; }
        public string NBEApprovalRefNumber { get; set; }
        public string QueueRound { get; set; }
        public string QueueNumber { get; set; }
        public string OwnSourceValue { get; set; }
        public string CurrencyRateValue { get; set; }
        [Display(Name = "Amount")]
        [RegularExpression(@"^(\-)?\d{1,3}(?:,\d{3})*(?:\.\d{1,6})?$", ErrorMessage = "Amount should be a number greater than 0.")]
        public string AmountValue { get; set; }
        [Display(Name = "USD Rate")]
        public string USDRateValue { get; set; }
        [Display(Name = "USD amount")]
        public string AmountInUSDValue { get; set; }
        [Display(Name = "ETB amount")]
        public string AmountInBirrValue { get; set; }
        public string CurrencyType { get; set; }
        public Guid MerchantId { get; set; }
        public Nullable<decimal> PreviousAmountValue { get; set; }
        public string CreatedByFullName { get; set; }
        public List<tblPermit> ImportPOList { get; set; }
        public Nullable<System.Guid> MethodOfPaymentId { get; set; }
        public string MethodOfPaymentName { get; set; }
        //#
    }
}
