//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPermitAmountDetail
    {
        public tblPermitAmountDetail()
        {
            this.Id = Guid.NewGuid();
        }

        public System.Guid Id { get; set; }
        public System.Guid PermitAmountId { get; set; }
        public Nullable<decimal> CurrencyRate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> AmountInUSD { get; set; }
        public Nullable<decimal> AmountInBirr { get; set; }
        public Nullable<decimal> USDRate { get; set; }
    
        public virtual tblPermitAmount tblPermitAmount { get; set; }
    }
}
