//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.UserId = Guid.NewGuid();
            this.tblApplications = new HashSet<tblApplication>();
            this.tblApplicationAmounts = new HashSet<tblApplicationAmount>();
            this.tblApplicationAmounts1 = new HashSet<tblApplicationAmount>();
            this.tblPermits = new HashSet<tblPermit>();
            this.tblPermitAmounts = new HashSet<tblPermitAmount>();
            this.tblPermitAmounts1 = new HashSet<tblPermitAmount>();
            this.ROLES = new HashSet<ROLE>();
        }
    
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string IDNo { get; set; }
        public string Title { get; set; }
        public string Initial { get; set; }
        public string EMail { get; set; }
    
        public virtual ICollection<tblApplication> tblApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicationAmount> tblApplicationAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblApplicationAmount> tblApplicationAmounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermit> tblPermits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermitAmount> tblPermitAmounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPermitAmount> tblPermitAmounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLE> ROLES { get; set; }
    }
}
