//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZB_FEPMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZB_FEPMS_Model : DbContext
    {
        public ZB_FEPMS_Model()
            : base("name=ZB_FEPMS_Model")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLog> AccessLogs { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONS { get; set; }
        public virtual DbSet<ROLE> ROLES { get; set; }
        public virtual DbSet<SETTING> SETTINGs { get; set; }
        public virtual DbSet<tbl_lu_CountryOfOrigin> tbl_lu_CountryOfOrigin { get; set; }
        public virtual DbSet<tbl_lu_Incoterm> tbl_lu_Incoterm { get; set; }
        public virtual DbSet<tbl_lu_MethodOfPayment> tbl_lu_MethodOfPayment { get; set; }
        public virtual DbSet<tbl_lu_PortOfDestination> tbl_lu_PortOfDestination { get; set; }
        public virtual DbSet<tbl_lu_PortOfLoading> tbl_lu_PortOfLoading { get; set; }
        public virtual DbSet<tbl_lu_ShipmentAllowedBy> tbl_lu_ShipmentAllowedBy { get; set; }
        public virtual DbSet<tbl_lu_Status> tbl_lu_Status { get; set; }
        public virtual DbSet<tblApplicant> tblApplicants { get; set; }
        public virtual DbSet<tblApplication> tblApplications { get; set; }
        public virtual DbSet<tblApplicationAmount> tblApplicationAmounts { get; set; }
        public virtual DbSet<tblItemPriority> tblItemPriorities { get; set; }
        public virtual DbSet<tblMerchant> tblMerchants { get; set; }
        public virtual DbSet<tblPermit> tblPermits { get; set; }
        public virtual DbSet<tblPermitAmount> tblPermitAmounts { get; set; }
        public virtual DbSet<tblPermitAmountDetail> tblPermitAmountDetails { get; set; }
        public virtual DbSet<tblPOPermitAmountDetail> tblPOPermitAmountDetails { get; set; }
        public virtual DbSet<tblPOPermitDetail> tblPOPermitDetails { get; set; }
        public virtual DbSet<tblPOPermitExpiry> tblPOPermitExpiries { get; set; }
        public virtual DbSet<tblSerialNumberShelf> tblSerialNumberShelves { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
